Repository 2024-Summer-Techeer-BootCamp-Team-E/backend, pull requests merged in 2024-07, with the labels that each got.

#7 [Refactor/#6] user app 생성
  django_backend/__pycache__/__init__.cpython-310.pyc
  django_backend/__pycache__/__init__.cpython-311.pyc
  django_backend/__pycache__/settings.cpython-310.pyc
  django_backend/__pycache__/settings.cpython-311.pyc
  django_backend/__pycache__/urls.cpython-310.pyc
  django_backend/__pycache__/wsgi.cpython-310.pyc
  django_backend/settings.py
  django_backend/urls.py
  newapp/models.py
  product/__init__.py
  product/__pycache__/__init__.cpython-310.pyc
  product/__pycache__/admin.cpython-310.pyc
  product/__pycache__/apps.cpython-310.pyc
  product/__pycache__/models.cpython-310.pyc
  product/__pycache__/urls.cpython-310.pyc
  product/__pycache__/views.cpython-310.pyc
  product/admin.py
  product/apps.py
  product/migrations/0001_initial.py
  product/migrations/__init__.py
  product/migrations/__pycache__/0001_initial.cpython-310.pyc
  product/migrations/__pycache__/__init__.cpython-310.pyc
  product/models.py
  product/tests.py
  product/urls.py
  product/views.py
  user/__init__.py
  user/__pycache__/__init__.cpython-310.pyc
  user/__pycache__/admin.cpython-310.pyc
  user/__pycache__/apps.cpython-310.pyc
  user/__pycache__/models.cpython-310.pyc
  user/admin.py
  user/apps.py
  user/migrations/__init__.py
  user/migrations/__pycache__/__init__.cpython-310.pyc
  user/models.py
  user/tests.py
  user/views.py
Labels: 🧹 Refactor

#11 feat : 상품정보 SELECT 구현
  django_backend/__pycache__/settings.cpython-310.pyc
  django_backend/requirements.txt
  django_backend/settings.py
  product/__pycache__/admin.cpython-310.pyc
  product/__pycache__/ali.cpython-310.pyc
  product/__pycache__/serializers.cpython-310.pyc
  product/__pycache__/urls.cpython-310.pyc
  product/__pycache__/views.cpython-310.pyc
  product/admin.py
  product/ali.py
  product/serializers.py
  product/urls.py
  user/__init__.py
  user/__pycache__/__init__.cpython-310.pyc
  user/__pycache__/admin.cpython-310.pyc
  user/__pycache__/apps.cpython-310.pyc
  user/__pycache__/models.cpython-310.pyc
  user/admin.py
  user/apps.py
  user/migrations/__init__.py
  user/migrations/__pycache__/__init__.cpython-310.pyc
  user/models.py
  user/tests.py
  user/views.py
Labels: 🚀 Feat

#13 feat:회원가입 로그인 구현
  .gitignore
  accounts/__init__.py
  accounts/migrations/0001_initial.py
  accounts/migrations/__init__.py
  accounts/models.py
  accounts/serializers.py
  accounts/urls.py
  accounts/views.py
  django_backend/requirements.txt
  django_backend/settings.py
  django_backend/urls.py
Labels: 🚀 Feat

#27 [refactor] accounts model
  accounts/__pycache__/managers.cpython-310.pyc
  accounts/__pycache__/models.cpython-310.pyc
  accounts/__pycache__/serializers.cpython-310.pyc
  accounts/managers.py
  accounts/migrations/0001_initial.py
  accounts/migrations/__pycache__/0001_initial.cpython-310.pyc
  accounts/models.py
  accounts/serializers.py
Labels: 🧹 Refactor

#30 [Feat/#28] Ali API 기능 구현, Accounts 모델 변경
  accounts/__pycache__/models.cpython-310.pyc
  accounts/__pycache__/serializers.cpython-310.pyc
  accounts/migrations/0001_initial.py
  accounts/migrations/__pycache__/0001_initial.cpython-310.pyc
  accounts/models.py
  accounts/serializers.py
  django_backend/__pycache__/urls.cpython-310.pyc
  django_backend/urls.py
  likeProducts/__pycache__/models.cpython-310.pyc
  likeProducts/__pycache__/serializers.cpython-310.pyc
  likeProducts/__pycache__/views.cpython-310.pyc
  likeProducts/migrations/0001_initial.py
  likeProducts/migrations/__pycache__/0001_initial.cpython-310.pyc
  likeProducts/models.py
  likeProducts/serializers.py
  likeProducts/views.py
  products/__pycache__/ali.cpython-310.pyc
  products/__pycache__/models.cpython-310.pyc
  products/__pycache__/serializers.cpython-310.pyc
  products/__pycache__/urls.cpython-310.pyc
  products/__pycache__/views.cpython-310.pyc
  products/ali.py
  products/example_get_product.py
  products/jsonExample
  products/migrations/0001_initial.py
  products/migrations/__pycache__/0001_initial.cpython-310.pyc
  products/models.py
  products/serializers.py
  products/urls.py
  products/views.py
  search/migrations/0001_initial.py
  search/models.py
Labels: 🚀 Feat

#35 [Feat/#10] url 상품 정보 추출 api 구현 완료
  .DS_Store
  django_backend/Dockerfile
  django_backend/requirements.txt
  django_backend/urls.py
  products/__init__.py
  products/__pycache__/__init__.cpython-310.pyc
  products/__pycache__/admin.cpython-310.pyc
  products/__pycache__/ali.cpython-310.pyc
  products/__pycache__/apps.cpython-310.pyc
  products/__pycache__/models.cpython-310.pyc
  products/__pycache__/serializers.cpython-310.pyc
  products/__pycache__/urls.cpython-310.pyc
  products/__pycache__/views.cpython-310.pyc
  products/ali.py
  products/migrations/0001_initial.py
  products/migrations/__pycache__/0001_initial.cpython-310.pyc
  products/migrations/__pycache__/__init__.cpython-310.pyc
  products/models.py
  products/scrape.py
  products/serializers.py
  products/urls.py
  products/views.py
  search/migrations/0001_initial.py
  search/models.py
Labels: 🚀 Feat

#45 [refactor] Search 모델에 image_url 추가
  search/models.py
Labels: 🧹 Refactor

#47 [chore] 프론트엔드 도커 연동 완료
  docker-compose.yml
Labels: 🧭 Chore

#48 [feat] redis 관련 설정 추가, products 모델 변경, api 수정
  .gitignore
  accounts/__pycache__/managers.cpython-310.pyc
  accounts/__pycache__/models.cpython-310.pyc
  accounts/__pycache__/serializers.cpython-310.pyc
  accounts/migrations/__pycache__/0001_initial.cpython-310.pyc
  django_backend/__pycache__/settings.cpython-310.pyc
  django_backend/__pycache__/settings.cpython-311.pyc
  django_backend/__pycache__/urls.cpython-310.pyc
  django_backend/requirements.txt
  django_backend/settings.py
  django_backend/urls.py
  docker-compose.yml
  likeProducts/__pycache__/models.cpython-310.pyc
  likeProducts/__pycache__/serializers.cpython-310.pyc
  likeProducts/__pycache__/urls.cpython-310.pyc
  likeProducts/__pycache__/views.cpython-310.pyc
  likeProducts/migrations/0001_initial.py
  likeProducts/migrations/__pycache__/0001_initial.cpython-310.pyc
  likeProducts/models.py
  likeProducts/serializers.py
  likeProducts/views.py
  products/admin.py
  products/ali.py
  products/migrations/0001_initial.py
  products/models.py
  products/serializers.py
  products/tests.py
  products/views.py
  search/migrations/0002_search_image_url.py
  search/serializers.py
Labels: 🚀 Feat

#60 [Feat] url 중복 저장 방지
  products/views.py
Labels: 🚀 Feat

#62 [Feat] 중복 url 정보 출력
  products/views.py
Labels: 🚀 Feat

#66 [Feat/65] 좋아요 상품 비교 url 가격 추가
  likeProducts/models.py
  likeProducts/serializers.py
  likeProducts/views.py
Labels: 🚀 Feat

#71 [Refactor/#70] cd 개선
  .github/workflows/cd.yml
Labels: 🧹 Refactor

#73 [Hotfix/#1] .env 파일 삭제
  products/.env
Labels: 🔥 Hotfix

#77 [Chore/#74]cd 수정
  .github/workflows/cd.yml
Labels: 🧭 Chore

#85 [Hotfix] docker compose 프론트앤드 연결
  docker-compose.yml
Labels: 🔥 Hotfix

#88 [Fix/#87] cd 수정
  .github/workflows/cd.yml
Labels: 🏷 Fix

#98 [Feat/#64] 비동기 처리 구현 완료
  django_backend/Dockerfile
  django_backend/__init__.py
  django_backend/celery.py
  django_backend/celery_setting
  django_backend/requirements.txt
  django_backend/settings.py
  docker-compose.yml
  grafana/data/grafana.db
  nginx/nginx.conf
  products/ali.py
  products/tasks.py
  products/urls.py
  products/views.py
  search/tasks.py
Labels: 🚀 Feat
